### ISSUE TITLE
Please add a license file

### ISSUE THREAD

**Issue by unixorn** [eddieantonio/gitbash-zsh-theme#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license file.

Please add a license file - if you don't have one in mind,  I recommend using [choosealicense.com](https://choosealicense.com) to help choose an appropriate one.

Thanks!

**Comment by eddieantonio** [comment]
@unixorn Done!

Fun fact! I wanted to match git-sdk-64's license, [but they don't appear to have a LICENSE or COPYING file](https://github.com/git-for-windows/git-sdk-64) :/
